version: "3.1"

services:
    mongodb:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./mongodb_docker/data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: adminadmin
